/** Codes for SaasSubscriptionLog.step — filterable in Admin */
export const SAAS_SUBSCRIPTION_LOG_STEP = {
  STRIPE_KEY_MISSING: "STRIPE_KEY_MISSING",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  NO_COMPANY: "NO_COMPANY",
  NO_PLAN_RESOLVED: "NO_PLAN_RESOLVED",
  NO_STRIPE_PRICE_ID: "NO_STRIPE_PRICE_ID",
  TOTAL_MISMATCH: "TOTAL_MISMATCH",
  PAYMENT_METHOD_NOT_FOUND: "PAYMENT_METHOD_NOT_FOUND",
  SUCCESS: "SUCCESS",
  STRIPE_OR_SERVER_ERROR: "STRIPE_OR_SERVER_ERROR",
} as const;

export type SaasSubscriptionLogStep =
  (typeof SAAS_SUBSCRIPTION_LOG_STEP)[keyof typeof SAAS_SUBSCRIPTION_LOG_STEP];
