/**
 * Tipos de negocio para búsqueda en Google Places (Text Search).
 * label: para el dropdown en UI. value: término de búsqueda en español para la API.
 * Basado en tipos soportados por Google Maps / Places.
 */
export const GOOGLE_PLACE_CATEGORIES = [
  { value: "abogados", label: "Abogados" },
  { value: "agencias de viajes", label: "Agencias de viajes" },
  { value: "autoescuelas", label: "Autoescuelas" },
  { value: "bancos", label: "Bancos" },
  { value: "bares", label: "Bares" },
  { value: "cafeterías", label: "Cafeterías" },
  { value: "carpinterías", label: "Carpinterías" },
  { value: "clínicas", label: "Clínicas" },
  { value: "dentistas", label: "Dentistas" },
  { value: "electricistas", label: "Electricistas" },
  { value: "electrónica", label: "Electrónica" },
  { value: "escuelas", label: "Escuelas" },
  { value: "farmacias", label: "Farmacias" },
  { value: "ferreterías", label: "Ferreterías" },
  { value: "florerías", label: "Florerías" },
  { value: "funerarias", label: "Funerarias" },
  { value: "gasolineras", label: "Gasolineras" },
  { value: "gimnasios", label: "Gimnasios" },
  { value: "gimnasios de box", label: "Gimnasios de box" },
  { value: "guarderías", label: "Guarderías" },
  { value: "hoteles", label: "Hoteles" },
  { value: "iglesias", label: "Iglesias" },
  { value: "inmobiliarias", label: "Inmobiliarias" },
  { value: "joyerías", label: "Joyerías" },
  { value: "laboratorios", label: "Laboratorios" },
  { value: "lavanderías", label: "Lavanderías" },
  { value: "librerías", label: "Librerías" },
  { value: "médicos", label: "Médicos" },
  { value: "mueblerías", label: "Mueblerías" },
  { value: "mudanzas", label: "Mudanzas" },
  { value: "negocios locales", label: "Negocios locales" },
  { value: "ópticas", label: "Ópticas" },
  { value: "panaderías", label: "Panaderías" },
  { value: "pastelerías", label: "Pastelerías" },
  { value: "peluquerías", label: "Peluquerías" },
  { value: "plomeros", label: "Plomeros" },
  { value: "restaurantes", label: "Restaurantes" },
  { value: "salones de belleza", label: "Salones de belleza" },
  { value: "seguros", label: "Seguros" },
  { value: "spa", label: "Spa" },
  { value: "supermercados", label: "Supermercados" },
  { value: "talleres mecánicos", label: "Talleres mecánicos" },
  { value: "tiendas de mascotas", label: "Tiendas de mascotas" },
  { value: "tiendas de ropa", label: "Tiendas de ropa" },
  { value: "veterinarias", label: "Veterinarias" },
  { value: "otra", label: "Otra" },
] as const;
