export const USER_AUTH_LOG_SOURCE = {
  REGISTER_USER: "REGISTER_USER",
  CUSTOM_AUTH: "CUSTOM_AUTH",
  GOOGLE_AUTH: "GOOGLE_AUTH",
} as const;

export type UserAuthLogSource =
  (typeof USER_AUTH_LOG_SOURCE)[keyof typeof USER_AUTH_LOG_SOURCE];

/** Valores para UserAuthLog.step (filtrar en Admin) */
export const USER_AUTH_LOG_STEP = {
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL_INVALID_REFERRER: "REGISTER_FAIL_INVALID_REFERRER",
  REGISTER_FAIL: "REGISTER_FAIL",
  CUSTOM_AUTH_SIGNUP: "CUSTOM_AUTH_SIGNUP",
  CUSTOM_AUTH_LOGIN: "CUSTOM_AUTH_LOGIN",
  CUSTOM_AUTH_FAIL: "CUSTOM_AUTH_FAIL",
  GOOGLE_AUTH_SIGNUP: "GOOGLE_AUTH_SIGNUP",
  GOOGLE_AUTH_LOGIN: "GOOGLE_AUTH_LOGIN",
  GOOGLE_AUTH_FAIL: "GOOGLE_AUTH_FAIL",
} as const;
